openapi: "3.0.2"
info:
  title: API Posyandu Melati
  version: "1.0"
servers:
  - url: http://localhost:8000/api
tags:
  - name: Data edukasi
    description: Untuk mengola data edukasi
  - name: Data berita acara
    description: Untuk mengola data berita acara
paths:
  /edukasi:
    get:
      tags:
        - Data edukasi
      summary: MENDAPATKAN data edukasi

      requestBody:
        description: Data edukasi untuk menghapus data edukasi
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_edukasi:
                  type: integer
                search:
                  type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_edukasi:
                    type: string
                  email:
                    type: string
                  nama_lengkap:
                    type: string
                  judul:
                    type: string
                  materi:
                    type: string
                  gambar:
                    type: string
                  tanggal:
                    type: string
        400:
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data ... tidak valid"
        404:
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data dengan id ... tidak ditemukan"
    post:
      tags:
        - Data edukasi
      summary: MENAMBAHKAN data edukasi
      requestBody:
        description: Data edukasi untuk menambahkan data edukasi
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_admin:
                  type: integer
                judul:
                  type: string
                materi:
                  type: string
                gambar:
                  type: string
                tanggal:
                  type: string
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                success:
                  message: "Data ... berhasil ditambahkan"
        400:
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data ... tidak valid"
    put:
      tags:
        - Data edukasi
      summary: MENGUBAH data edukasi
      requestBody:
        description: Data edukasi untuk mengubah data edukasi
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_edukasi:
                  type: integer
                judul:
                  type: string
                materi:
                  type: string
                gambar:
                  type: string
                tanggal:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                success:
                  message: "Data ... berhasil diubah"
        400:
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data ... tidak valid"
        404:
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data dengan id ... tidak ditemukan"
    delete:
      tags:
        - Data edukasi
      summary: MENGHAPUS data edukasi
      requestBody:
        description: Data edukasi untuk menghapus data edukasi
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_edukasi:
                  type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                success:
                  message: "Data ... berhasil dihapus"
        404:
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data dengan id ... tidak ditemukan"

  /berita:
    get:
      tags:
        - Data berita acara
      summary: MENDAPATKAN data berita

      requestBody:
        description: Data berita untuk menghapus data berita
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_berita:
                  type: integer
                search:
                  type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_berita:
                    type: integer
                  email:
                    type: string
                  nama_lengkap:
                    type: string
                  judul:
                    type: string
                  desskripsi:
                    type: string
                  gambar:
                    type: string
                  tanggal_pelaksanaan:
                    type: string
        400:
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data ... tidak valid"
        404:
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data dengan id ... tidak ditemukan"
    post:
      tags:
        - Data berita acara
      summary: MENAMBAHKAN data berita
      requestBody:
        description: Data berita untuk menambahkan data berita
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_admin:
                  type: integer
                judul:
                  type: string
                desskripsi:
                  type: string
                gambar:
                  type: string
                tanggal_pelaksanaan:
                  type: string
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                success:
                  message: "Data ... berhasil ditambahkan"
        400:
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data ... tidak valid"
    put:
      tags:
        - Data berita acara
      summary: MENGUBAH data berita
      requestBody:
        description: Data berita untuk mengubah data berita
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_berita:
                  type: integer
                judul:
                  type: string
                desskripsi:
                  type: string
                gambar:
                  type: string
                tanggal_pelaksanaan:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                success:
                  message: "Data ... berhasil diubah"
        400:
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data ... tidak valid"
        404:
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data dengan id ... tidak ditemukan"
    delete:
      tags:
        - Data berita acara
      summary: MENGHAPUS data berita
      requestBody:
        description: Data berita untuk menghapus data berita
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_berita:
                  type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                success:
                  message: "Data ... berhasil dihapus"
        404:
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
              example:
                errors:
                  message: "Data dengan id ... tidak ditemukan"
